version: '3.8'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./registry-data:/data
    restart: always

  # Interfaz web para visualizar el registro (opcional)
  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: docker-registry-ui
    ports:
      - "8081:80"
    environment:
      - REGISTRY_TITLE=Mi Registro Docker Privado
      - REGISTRY_URL=http://registry:5000
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    restart: always
